### ISSUE TITLE
Notices on "add to cart" with SellStrom 

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/sellstrom#8]
Hi,

When I try to add a product to the cart, I get the following list of notices.

![capture du 2014-12-01 18 56 17](https://cloud.githubusercontent.com/assets/6768917/5250478/c6650664-798c-11e4-8eae-1e5949be8b21.png)

**Comment by prantikdasgupta** [comment]
Hello Thomas,
I have fixed the above issue and also we have added two new functionlity of add insurance and create invoice. I have committed all the changes by forking from the master. Following is the pull request, I have generated to merge the changes.
https://github.com/PrestaShop/sellstrom/pull/9
Now, I am not sure how to merge it to the main master.

Secondly, while validating the module against https://validator.prestashop.com, I am getting the following error. I could not find any documentation to resolve the issue.
![image](https://cloud.githubusercontent.com/assets/9323871/6141899/b783dc96-b1d2-11e4-802b-b8d8d9c16f61.png)

Could you please help me to merge and resolve the above issue?

Thanks,
Prantik

**Comment by prantikdasgupta** [comment]
Hello Thomas,
I have fixed the review comments for the Pull Request: #9.
Could you please review and let me know if there are any more changes to be done?
Also, I am not sure how to get pass the CURL extension error in Prestashop validator.

Thanks,
Prantik

**Comment by prantikdasgupta** [comment]
Hello Thomas,
This issue was fixed in the Pull request #9. Can you please close this issue?

Thanks,
Prantik

**Comment by Quetzacoalt91** [comment]
Hi,

Indeed, we can close this issue. Thanks
